### ISSUE TITLE
Propose: Cypress for e2e testing

### ISSUE THREAD

**Issue by ghost** [kudos-dude/react-best-practices#3]
No direct experience with Sinon, so can't comment on whether or not its better, but Ive seen a lot of new projects praise [Cypress](https://www.cypress.io/) as a solid e2e testing engine with a ton of quality-of-life tooling.

**Comment by kudos-dude** [comment]
Haven't heard of that one yet, but it's definitely worth a look! I'll add it to my TODO :-)

**Comment by kudos-dude** [comment]
This looks very cool. This looks like a great library that could be used to create an automated testing suite with in browser controls and output. Adding to the guide now

👍
