### ISSUE TITLE
Proposal to add dayjs as a date helper

### ISSUE THREAD

**Issue by Amandeepsinghghai** [kudos-dude/react-best-practices#5]
First of all thanks for the repo! Really appreciate it.

I was wondering if [dayjs](https://github.com/iamkun/dayjs) could be added to the list? It is a much smaller alternative to moment.

**Comment by kudos-dude** [comment]
Cheers!

Looks like a useful alternative and is definitely popular. I'll add it to the list

**Comment by Amandeepsinghghai** [comment]
@kudos-dude Awesome! GGWP!
